trigger:
- master

variables:
  BuildConfiguration: Release
  DotNetSdkVersion: 3.1.x
  BundlePlatforms: x86|x64
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'WinQuickLook.Package_StoreKey.pfx'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(DotNetSdkVersion)'

- task: MSBuild@1
  inputs:
    solution: '**/*.wapproj'
    configuration: 'Release'
    msbuildArguments: |
      /p:Configuration=Release
      /p:UapAppxPackageBuildMode=StoreUpload
      /p:AppxBundlePlatforms="$(BundlePlatforms)"
      /p:AppxPackageDir="$(Build.SourcesDirectory)/packed"
      /p:AppxBundle=Always
      /p:UapAppxPackageBuildMode=CI
      /p:AppxPackageSigningEnabled=true
      /p:PackageCertificateThumbprint=""
      /p:PackageCertificateKeyFile="$(Build.SourcesDirectory)/WinQuickLook.Package_StoreKey.pfx"'
    restoreNugetPackages: true

- publish: packed
  artifact: msix