trigger:
- master

variables:
- group: Secrets
- name: BuildConfiguration
  value: Release
- name: DotNetSdkVersion
  value: 3.1.x
- name: BundlePlatforms
  value: x86|x64

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  name: signingCert
  inputs:
    secureFile: 'WinQuickLook.pfx'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(DotNetSdkVersion)'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'

- task: MSBuild@1
  inputs:
    solution: '**/*.wapproj'
    configuration: 'Release'
    msbuildArguments: |
      /p:Configuration=Release
      /p:UapAppxPackageBuildMode=StoreUpload
      /p:AppxBundlePlatforms="$(BundlePlatforms)"
      /p:AppxPackageDir="$(Build.SourcesDirectory)/packed"
      /p:AppxBundle=Always
      /p:UapAppxPackageBuildMode=CI
      /p:AppxPackageSigningEnabled=true
      /p:PackageCertificateThumbprint=""
      /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)"
      /p:PackageCertificatePassword="$(PfxPassword)"

- publish: packed
  artifact: msix